docs/source/contributing.rst
docs/source/index.rst

Basic contributing welcome doc page

---

qtrio/__init__.py
qtrio/_core.py
qtrio/_exceptions.py
qtrio/_pytest.py
qtrio/_tests/test_pytest.py

Shift test timeout into Trio

---

ci.sh
docs/source/development/reviewing.rst
newsfragments/10.misc.rst
pyproject.toml
setup.py
towncrier.toml

Require newsfragments

---

.github/workflows/ci.yml
ci.sh
mypy.ini
newsfragments/41.misc.rst
qtrio/_core.py
setup.py

Preliminary mypy

---

docs/source/core.rst
docs/source/exceptions.rst
newsfragments/38.misc.rst
qtrio/__init__.py
qtrio/_core.py
qtrio/_exceptions.py
qtrio/_tests/test_core.py
qtrio/_tests/test_qt.py

Privatize and tidy

---

ci.sh
docs/source/development/releasing.rst
newsfragments/38.misc.rst
newsfragments/88.misc.rst
newsfragments/README.rst
towncrier.toml

Workaround for https://github.com/twisted/towncrier/pull/271.  To be cleaned up in #89.

Towncrier project name

---

docs/source/core.rst
mypy.ini
newsfragments/57.feature.rst
qtrio/__init__.py
qtrio/_core.py
qtrio/_tests/test_core.py

Preliminary open_emissions_nursery()

---

ci.sh
newsfragments/117.misc.rst

https://github.com/nedbat/coveragepy/issues/1015
https://github.com/python-trio/trio/commit/02066df418baab1656dec640ff0a17e0f1085a22

copy .coveragerc so codecov finds it

---

.coveragerc
docs/source/conf.py
mypy.ini
newsfragments/114.feature.rst
newsfragments/116.feature.rst
qtrio/_core.py
qtrio/_pytest.py
qtrio/_tests/test_pytest.py
qtrio/examples/_tests/docs/test_qtrio_host.py
setup.py

Workarounds:
- sphinx-doc/sphinx#8015 to be removed in #118
- micheles/decorator#39 to be removed in #119

Use decorator.decorator for optional call on qtrio.host

---

docs/source/conf.py
docs/source/core.rst
docs/source/exceptions.rst
newsfragments/146.doc.rst
qtrio/__init__.py
qtrio/_core.py
qtrio/_exceptions.py
qtrio/_python.py
qtrio/_qt.py
qtrio/_tests/test_core.py
qtrio/_tests/test_pytest.py
qtrio/examples/emissions.py
setup.py

Draft for:
- #148
- #149 
- #150 
- #151

Autodoc config ext

---

.github/workflows/ci.yml
.readthedocs.yml
docs/source/getting_started.rst
docs/source/index.rst
newsfragments/155.doc.rst
setup.py

Add installation section - Adjust extras

---

newsfragments/11.bugfix.rst
qtrio/_core.py
qtrio/_tests/test_core.py

Quiet down trio_done()

---

setup.py

https://github.com/sphinx-doc/sphinx/issues/8567

Exclude sphinx 3.4.0 and 3.4.1

---

README.rst
docs/source/examples/readme.rst
qtrio/_tests/examples/readme/test_console.py
qtrio/examples/readme/console.py

Describe readme examples

---

README.rst

Does something for #222 but is kind of a stop gap...

Code comments for where to find full runnable readme examples

---

setup.cfg

https://github.com/sphinx-doc/sphinx/issues/8880

Sphinx != 3.5.0

---

.gitignore

After following the [documentation](https://qtrio.readthedocs.io/en/stable/development/testing.html) on testing QTrio, I noted the following files/directories on my `git status` that should be ignored by git:
testvenv
test-results.xml

add test files to .gitignore

---

.github/workflows/ci.yml

https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
> - `*`: Matches zero or more characters, but does not match the `/` character. For example, `Octo*` matches `Octocat`.
> - `**`: Matches zero or more of any character.

ci: build pull requests against ** (_all_) branches

---

docs/source/conf.py
qtrio/_exceptions.py

https://github.com/sphinx-doc/sphinx/issues/7493

Drop __module__ = "qtrio"

---

docs/source/history.rst
newsfragments/123.misc.rst
newsfragments/251.breaking.rst
newsfragments/83.misc.rst
qtrio/_version.py

Prepare release v0.5.0 - use qts

---

ci.sh
docs/source/history.rst
newsfragments/267.feature.rst
pytest.ini
qtrio/_version.py

Prepare release v0.5.1
